// Generates src/eld/ngrams-m60.ts from the M60 ngrams dataset bundled in
// efficient-language-detector-no-dynamic-import (a devDependency, used only
// here and for parity verification — it is not deployed to the Worker).
//
// The upstream package embeds the ngrams data as a plain JS object literal,
// which V8 parses much slower at module-evaluation time than the equivalent
// JSON.parse(string) form. Regenerating it this way is the whole point of
// vendoring: see src/eld/README.md for background.
//
// Usage: npm run generate:ngrams

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ngramsData } from 'efficient-language-detector-no-dynamic-import/src/ngrams/ngramsM60.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outFile = path.join(__dirname, '../src/eld/ngrams-m60.ts');

// Double-stringify so JSON.parse gets back a single JS string literal.
// This safely escapes the non-ASCII characters that appear in ngram keys
// (ELD's byte-dictionary maps raw bytes to characters like ä, ü, ß, …).
const json = JSON.stringify(ngramsData);
const literal = JSON.stringify(json);

const output = `// Generated by scripts/generate-ngrams.mjs — do not edit by hand.
// Source: efficient-language-detector-no-dynamic-import (M60 dataset), Apache-2.0.
// See src/eld/README.md.

import type { NgramsData } from './types';

export const ngramsData: NgramsData = JSON.parse(${literal});
`;

fs.writeFileSync(outFile, output);

// Sanity check: round-trip must reproduce the exact same data.
const roundTripped = JSON.parse(json);
if (JSON.stringify(roundTripped) !== json) {
  throw new Error(
    'Round-trip check failed: generated data does not match source',
  );
}

console.log(`Wrote ${outFile} (${(output.length / 1e6).toFixed(2)} MB)`);
